//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobworldToolboxCe {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobworldToolboxCe.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images.CreateLogicalGroups16x16.bmp ähnelt.
        /// </summary>
        internal static string CREATELOGICALGROUPS_BITMAP {
            get {
                return ResourceManager.GetString("CREATELOGICALGROUPS_BITMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Robworld ähnelt.
        /// </summary>
        internal static string CREATELOGICALGROUPS_CATEGORY {
            get {
                return ResourceManager.GetString("CREATELOGICALGROUPS_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create logical groups from variant names in object tree or from prototype name ähnelt.
        /// </summary>
        internal static string CREATELOGICALGROUPS_DESCRIPTION {
            get {
                return ResourceManager.GetString("CREATELOGICALGROUPS_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images.CreateLogicalGroups32x32.png ähnelt.
        /// </summary>
        internal static string CREATELOGICALGROUPS_LARGEBITMAP {
            get {
                return ResourceManager.GetString("CREATELOGICALGROUPS_LARGEBITMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create logical groups ähnelt.
        /// </summary>
        internal static string CREATELOGICALGROUPS_NAME {
            get {
                return ResourceManager.GetString("CREATELOGICALGROUPS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create logical groups from variant names in object tree or from prototype name ähnelt.
        /// </summary>
        internal static string CREATELOGICALGROUPS_TOOLTIP {
            get {
                return ResourceManager.GetString("CREATELOGICALGROUPS_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Robworld ähnelt.
        /// </summary>
        internal static string MFGIMPORTEXPORT_CATEGORY {
            get {
                return ResourceManager.GetString("MFGIMPORTEXPORT_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images.MfgExport16x16.bmp ähnelt.
        /// </summary>
        internal static string MFGIMPORTEXPORT_EXPORT_BITMAP {
            get {
                return ResourceManager.GetString("MFGIMPORTEXPORT_EXPORT_BITMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export Mfg data to the file system ähnelt.
        /// </summary>
        internal static string MFGIMPORTEXPORT_EXPORT_DESCRIPTION {
            get {
                return ResourceManager.GetString("MFGIMPORTEXPORT_EXPORT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images.MfgExport32x32.png ähnelt.
        /// </summary>
        internal static string MFGIMPORTEXPORT_EXPORT_LARGEBITMAP {
            get {
                return ResourceManager.GetString("MFGIMPORTEXPORT_EXPORT_LARGEBITMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MfgExport ähnelt.
        /// </summary>
        internal static string MFGIMPORTEXPORT_EXPORT_NAME {
            get {
                return ResourceManager.GetString("MFGIMPORTEXPORT_EXPORT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export Mfg data to the file system ähnelt.
        /// </summary>
        internal static string MFGIMPORTEXPORT_EXPORT_TOOLTIP {
            get {
                return ResourceManager.GetString("MFGIMPORTEXPORT_EXPORT_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images.MfgImport16x16.bmp ähnelt.
        /// </summary>
        internal static string MFGIMPORTEXPORT_IMPORT_BITMAP {
            get {
                return ResourceManager.GetString("MFGIMPORTEXPORT_IMPORT_BITMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import Mfgs from the file system to the study ähnelt.
        /// </summary>
        internal static string MFGIMPORTEXPORT_IMPORT_DESCRIPTION {
            get {
                return ResourceManager.GetString("MFGIMPORTEXPORT_IMPORT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Images.MfgImport32x32.png ähnelt.
        /// </summary>
        internal static string MFGIMPORTEXPORT_IMPORT_LARGEBITMAP {
            get {
                return ResourceManager.GetString("MFGIMPORTEXPORT_IMPORT_LARGEBITMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MfgImport ähnelt.
        /// </summary>
        internal static string MFGIMPORTEXPORT_IMPORT_NAME {
            get {
                return ResourceManager.GetString("MFGIMPORTEXPORT_IMPORT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import Mfgs from the file system to the study ähnelt.
        /// </summary>
        internal static string MFGIMPORTEXPORT_IMPORT_TOOLTIP {
            get {
                return ResourceManager.GetString("MFGIMPORTEXPORT_IMPORT_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mfg import/export ähnelt.
        /// </summary>
        internal static string MFGIMPORTEXPORT_NAME {
            get {
                return ResourceManager.GetString("MFGIMPORTEXPORT_NAME", resourceCulture);
            }
        }
    }
}
